// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"
)

type Player struct {
	SteamID          sql.NullInt64
	Visibility       int64
	RealName         string
	AccountCreatedOn time.Time
	AvatarHash       string
	CommunityBanned  int64
	GameBans         int64
	VacBans          int64
	LastVacBanOn     sql.NullTime
	KillsOn          int64
	DeathsBy         int64
	RageQuits        int64
	Notes            string
	Whitelist        bool
	ProfileUpdatedOn time.Time
	CreatedOn        time.Time
	UpdatedOn        time.Time
}

type PlayerMessage struct {
	MessageID int64
	SteamID   int64
	Message   string
	CreatedOn time.Time
}

type PlayerName struct {
	NameID    int64
	SteamID   int64
	Name      string
	CreatedOn time.Time
}
